### ISSUE TITLE
Can't update to 1.23 (file not found)

### ISSUE THREAD

**Issue by Pendragon77** [cospav/PdfScanManager#2]
I try to update via the updater but the linked file
https://www.dropbox.com/s/dl/sp5vatc4prs3dpg/PdfScanManager_Setup.exe
cannot be found.
So I am stuck with the 1.22.

**Comment by cospav** [comment]
Oops, dropbox link is broken...
You can download now from GitHub directly https://github.com/cospav/PdfScanManager/blob/main/PdfScanManager_Setup.exe
