### ISSUE TITLE
1.23setup contains exe from 1.22

### ISSUE THREAD

**Issue by Pendragon77** [cospav/PdfScanManager#3]
In the provided installer from today is the 1.22 exe from the 15.12.2020. Therefore an update request is stated while starting the program.

**Comment by Pendragon77** [comment]
![Zwischenablagebild](https://user-images.githubusercontent.com/76468662/102869561-179fb080-443c-11eb-9abd-6425b9f2e5bf.jpg)

Uninstalled and installed it again

**Comment by cospav** [comment]
You are right, thanks, Please try again 
(I have re uploaded on GitHub and Dropbox for auto updater)
