### ISSUE TITLE
Type in Filename not possible any more

### ISSUE THREAD

**Issue by kiggaaa** [cospav/PdfScanManager#4]
Hi!

Since one of the last updates, I cannot type in a filename properly any more. When starting to type in a filename (e.g. starting with "2" for adding the date at the beginning), the name is immediately changed automatically to a filename that I used some time before (like some kind of auto-correction). No way to edit this filename, always it changes back to the wrong name. Unfortunately, the software is useless now :( Very sorry about that, because I used it frequently!

Would be happy if there was a solution.

Greetings!

**Comment by cospav** [comment]
Hi kiggaaa,
please make sure you are using the most recent version 1.23, available in Code section.
Here you are able to change the auto-fill [mode ](https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.textbox.autocompletemode?view=net-5.0)in the settings - also to "none".
Good luck!

**Comment by kiggaaa** [comment]
Thanks, seems to work now although AutoCompleteMode was "none" already. But there was 1 entry in the Auto-Complete-List which I deleted.
